

```{r}
library(dplyr)
library(ggplot2)
library(cowplot)

data<-read.csv("../../../results/growth_curve_output.csv")


data_stats<-read.csv("../../../results/growth_curve_stats_output.csv")


pal<-c("#404040",
       "#4c7c2d",
       "#35979e",
       "#edac0f",
       "#f26e33",
       "#75da92",
       "#fe7aa8",
       "#adc4f5",
       "#ecd3f8") 


darker_colors <- c("#262626",
                   "#2e4a1b", 
                   "#205b5f",
                   "#8e6709",
                   "#91421f", 
                   "#468358",
                   "#984965",
                   "#687693",
                   "#8e7f95")
```

```{r}


#ERG3 complementation at different SDS concentrations

#Filter data to only take what we need
a_data<-data_stats%>%filter(strain == "Tet-O7-ERG3" & temperature == 30)

#Reorder data
target_order<-c("pRS315", "pRS315-ScerERG3", "pRS315-CalbERG3", "pRS315-CaurERG3", "pRS315-NglaERG3", "pRS315-CparERG3", "pRS315-CtroERG3")
new_labels<-c("Empty plasmid", "ScERG3", "CalERG3", "CauERG3", "NgERG3", "CpERG3", "CtERG3")
a_data$plasmid<-factor(a_data$plasmid,
                       levels = target_order,
                       labels = new_labels)

stress_order<-c("None", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
new_labels_stress<-c("No SDS", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
a_data$stress<-factor(a_data$stress,
                      levels=stress_order,
                      labels = new_labels_stress)


#Make plot
a<-a_data%>%
  ggplot(aes(y=plasmid, x=auc))+
  geom_boxplot(aes(fill=plasmid, color=plasmid))+
  scale_fill_manual(values=pal)+
  scale_color_manual(values=darker_colors)+
  scale_y_discrete(limits=rev(new_labels))+
  facet_wrap(vars(stress), ncol=1)+
  theme_bw()+
  theme(axis.text.x = element_text(colour="black"),
        axis.text.y = element_text(colour="black", face="italic"),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill= "white", colour= "white"),
        legend.position = "none")+
  labs(title = "ERG3 orthologs", y=NULL, x="AUC (Growth curves)")


```

```{r}


#ERG6 complementation at different SDS concentrations

#Filter data to only take what we need
b_data<-data_stats%>%filter(strain == "Tet-O7-ERG6" & temperature == 30)


#Reorder data
target_order<-c("pRS315", "pRS315-ScerERG6", "pRS315-CalbERG6", "pRS315-CaurERG6", "pRS315-NglaERG6", "pRS315-CparERG6", "pRS315-CtroERG6")
new_labels<-c("Empty plasmid", "ScERG6", "CalERG6", "CauERG6", "NgERG6", "CpERG6", "CtERG6")
b_data$plasmid<-factor(b_data$plasmid,
                       levels = target_order,
                       labels = new_labels)

stress_order<-c("None", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
new_labels_stress<-c("No SDS", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
b_data$stress<-factor(b_data$stress,
                      levels=stress_order,
                      labels = new_labels_stress)




#Make plot
b<-b_data%>%
  ggplot(aes(y=plasmid, x=auc))+
  geom_boxplot(aes(fill=plasmid, color=plasmid))+
  scale_fill_manual(values=pal)+
  scale_color_manual(values=darker_colors)+
  scale_y_discrete(limits=rev(new_labels))+
  facet_wrap(vars(stress), ncol=1)+
  theme_classic()+
  theme_bw()+
  theme(axis.text.x = element_text(colour="black"),
        axis.text.y = element_text(colour="black", face="italic"),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "white", colour= "white"),
        legend.position = "none")+
  labs(title = "ERG6 orthologs", y=NULL, x="AUC (Growth curves)")

```




```{r}

#Growth curves of ERG3 at different SDS concentrations 

#Filter data to only take what we need
c_data<-data%>%filter(strain == "Tet-O7-ERG3" & temperature == 30)

#Reorder data
target_order<-c("pRS315", "pRS315-ScerERG3", "pRS315-CalbERG3", "pRS315-CaurERG3", "pRS315-NglaERG3", "pRS315-CparERG3", "pRS315-CtroERG3")
new_labels<-c("Empty plasmid", "ScERG3", "CalERG3", "CauERG3", "NgERG3", "CpERG3", "CtERG3")
c_data$plasmid<-factor(c_data$plasmid,
                       levels = target_order,
                       labels = new_labels)

stress_order<-c("None", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
new_labels_stress<-c("No SDS", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
c_data$stress<-factor(c_data$stress,
                      levels=stress_order,
                      labels = new_labels_stress)

#Make plot
c<-c_data%>%
  ggplot(aes(x=Time, y=absorbance))+
  geom_smooth(method="gam",                      
              formula = y ~ s(x, bs = "cs"),     
              aes(fill=plasmid, colour=plasmid))+
  scale_fill_manual(values = pal)+
  scale_color_manual(values= pal)+
  facet_wrap(vars(stress), ncol=1)+
  theme_classic()+
  theme(panel.grid.major = element_line(colour="grey90"),
        strip.background = element_rect(colour= "white"),
        legend.text = element_text(colour="black", face="italic"))+
  labs(subtitle = "ERG3 orthologs",
       x="Time (h)",
       y="OD/mL",
       fill="Expressed ortholog",
       color="Expressed ortholog")

```



```{r}
#Growth curves of ERG6 at different SDS concentrations 

#Filter data to only take what we need
d_data<-data%>%filter(strain == "Tet-O7-ERG6" & temperature == 30)

#Reorder data
target_order<-c("pRS315", "pRS315-ScerERG6", "pRS315-CalbERG6", "pRS315-CaurERG6", "pRS315-NglaERG6", "pRS315-CparERG6", "pRS315-CtroERG6")
new_labels<-c("Empty plasmid", "ScERG6", "CalERG6", "CauERG6", "NgERG6", "CpERG6", "CtERG6")
d_data$plasmid<-factor(d_data$plasmid,
                       levels = target_order,
                       labels = new_labels)

stress_order<-c("None", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
new_labels_stress<-c("No SDS", "0.005% SDS", "0.0075% SDS", "0.01% SDS", "0.0125% SDS")
d_data$stress<-factor(d_data$stress,
                      levels=stress_order,
                      labels=new_labels_stress)




#Make plot
d<-d_data%>%
  ggplot(aes(x=Time, y=absorbance))+
  geom_smooth(method="gam",                      
              formula = y ~ s(x, bs = "cs"),     
              aes(fill=plasmid, colour=plasmid))+
  scale_fill_manual(values = pal)+
  scale_color_manual(values= pal)+
  facet_wrap(vars(stress), ncol=1)+
  theme_classic()+
  theme(panel.grid.major = element_line(colour="grey90"),
        strip.background = element_rect(colour= "white"),
        legend.text = element_text(colour="black", face="italic"))+
  labs(subtitle = "ERG6 orthologs",
       x="Time (h)",
       y="OD/mL",
       fill="Expressed ortholog",
       color="Expressed ortholog")

```

```{r}


assembled<-plot_grid(a,c,b,d,
          nrow=2, ncol=2,
          labels="auto")




save_plot(filename = "./FigS3_unmodified.svg", plot=assembled, base_width = 7, base_height = 14)





```

