
```{r}
#Load libraries
library(bio3d)
library(tidyverse)

#Read alignment fasta files (alignment from mafft)
erg3<-read.fasta("../data/Erg3_alignment.fasta")
erg6<-read.fasta("../data/Erg6_alignment.fasta")
erg11<-read.fasta("../data/Erg11_alignment.fasta")


```



```{r}

#Use  seqidentity from bio3d package to calculate the percentage of of sequence identity between aligned sequences

pid_erg3<-(seqidentity(erg3, normalize=TRUE)*100) #*100 to get percentage
pid_erg6<-(seqidentity(erg6, normalize = TRUE)*100)
pid_erg11<-(seqidentity(erg11, normalize = TRUE)*100)


#Quick overview of heatmaps
heatmap(pid_erg3)
heatmap(pid_erg6)
heatmap(pid_erg11)

```
```{r}

#Rearrange seqid matrices to long format data frames
long_pid_erg3<-pid_erg3%>%
  as.data.frame()%>%
  rownames_to_column(var="ortholog1")%>%
  pivot_longer(cols=-1, names_to = "ortholog2", values_to = "percent_id")

long_pid_erg6<-pid_erg6%>%
  as.data.frame()%>%
  rownames_to_column(var="ortholog1")%>%
  pivot_longer(cols=-1, names_to = "ortholog2", values_to = "percent_id")

long_pid_erg11<-pid_erg11%>%
  as.data.frame()%>%
  rownames_to_column(var="ortholog1")%>%
  pivot_longer(cols=-1, names_to = "ortholog2", values_to = "percent_id")
  


#Quick overview of heatmaps generated from long data frames as sanity check
long_pid_erg3%>%
  ggplot(aes(x=ortholog1, y=ortholog2, fill=percent_id))+
  geom_tile(colour="black")

long_pid_erg6%>%
  ggplot(aes(x=ortholog1, y=ortholog2, fill=percent_id))+
  geom_tile(colour="black")

long_pid_erg11%>%
  ggplot(aes(x=ortholog1, y=ortholog2, fill=percent_id))+
  geom_tile(colour="black")
```



```{r}


#Write seqid matrices
write.csv(pid_erg3, "../results/erg3_seqid.csv")
write.csv(pid_erg6, "../results/erg6_seqid.csv")
write.csv(pid_erg11, "../results/erg11_seqid.csv")

#write seqid long data frames
write.csv(long_pid_erg3, "../results/long_erg3_seqid.csv")
write.csv(long_pid_erg6, "../results/long_erg6_seqid.csv")
write.csv(long_pid_erg11, "../results/long_erg11_seqid.csv")
```

